name: Build Docker Folder Image

on:
  push:
    branches: [ "main" ]
    # 只有当 主文件夹 有变化时才触发
    paths:
      - 'nfne/**'
      - '.github/workflows/build-docker-image.yml'
  workflow_dispatch: # 允许你在网页上手动点击运行

env:
  REGISTRY: ghcr.io
  # 镜像名称
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 登录 GitHub 镜像仓库
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 生成标签 (latest 和 日期)
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha,prefix={{date 'YYYYMMDD'}}-{{sha:7}}-

      # 构建并推送
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          # 关键点：设置上下文为 hugging-face 文件夹
          context: ./nfne
          # Dockerfile 就在在这个文件夹里
          file: ./nfne/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
